# Generated by Django 3.2.9 on 2021-12-15 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Nazwa analizy')),
                ('analyst_name', models.CharField(max_length=64, verbose_name='Imię analityka')),
            ],
        ),
        migrations.CreateModel(
            name='Analyst',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('laboratory', models.IntegerField(choices=[(1, 'Organic'), (2, 'Non Organic'), (3, 'Research and development'), (4, 'Quality Control')])),
            ],
        ),
    ]
