# Generated by Django 3.2.9 on 2021-12-15 04:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notebook', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalystMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=254, verbose_name='Temat wiadomości')),
                ('content', models.TextField(verbose_name='Treść wiadomości')),
                ('date_sent', models.DateTimeField(auto_now_add=True, verbose_name='Data wysłania')),
                ('from_analyst', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notebook.analyst', verbose_name='Od')),
            ],
        ),
        migrations.CreateModel(
            name='AnalystNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=254, verbose_name='Temat Analizy/Badania')),
                ('content', models.TextField(verbose_name='Notatki z przeprowadzonego eksperymentu')),
                ('photos', models.ImageField(upload_to='photos')),
                ('date_sent', models.DateTimeField(auto_now_add=True, verbose_name='Data wysłania')),
                ('from_analyst', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notebook.analyst', verbose_name='Analityk')),
            ],
        ),
        migrations.CreateModel(
            name='Confirmation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('present', models.BooleanField(null=True)),
                ('analyst', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notebook.analyst')),
            ],
        ),
        migrations.CreateModel(
            name='Supervisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Laboratorium')),
                ('supervisor_name', models.CharField(max_length=64, verbose_name='Nazwisko Kierownika')),
            ],
        ),
        migrations.CreateModel(
            name='SupervisorMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=254, verbose_name='Temat wiadomości')),
                ('content', models.TextField(verbose_name='Treść wiadomości')),
                ('date_sent', models.DateTimeField(auto_now_add=True, verbose_name='Data wysłania')),
                ('from_supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notebook.supervisor', verbose_name='Kierownik')),
                ('to_analyst', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notebook.analyst', verbose_name='Do')),
            ],
        ),
        migrations.DeleteModel(
            name='AnalysisSubject',
        ),
        migrations.AddField(
            model_name='analystmessage',
            name='to_supervisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notebook.supervisor', verbose_name='Do'),
        ),
    ]
