# Generated by Django 3.2.9 on 2021-12-15 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notebook', '0002_auto_20211215_0443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analystnotice',
            name='photos',
            field=models.ImageField(blank=True, null=True, upload_to='photos'),
        ),
    ]
